version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Frontend
      - "8081:8081"  # Backend
    environment:
      NODE_ENV: production
      SHOPIFY_API_KEY: 1b25463d5663ca5b613611314ff105a5
